version: "3"
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data

  learn:
    image: isthisapple
    ports:
      - "5001:5001"
    depends_on:
      - redis
    volumes:
      - ..:/srv
    links:
      - redis
    working_dir: /srv/learn
    entrypoint:
      - gunicorn
      - learn:app
      - -b
      - 0.0.0.0:5001
