version: "2"
services:
  redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=change_it!!!
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"

  learn:
    image: isthisapple
    ports:
      - "5001:5001"
    depends_on:
      - redis
    volumes:
      - ..:/srv
    links:
      - redis
    working_dir: /srv/learn
    entrypoint:
      - gunicorn
      - learn:app
      - -b
      - 0.0.0.0:5001
